In [1]:
import datetime

In [3]:
now = datetime.datetime.now()
now

datetime.datetime(2018, 1, 25, 9, 43, 24, 35391)

In [10]:
now.strftime('%Y-%m-%d %H:%M:%S')

'2018-01-25 09:43:24'

In [9]:
datetime.__file__

'/Users/allieus/anaconda3/lib/python3.6/datetime.py'

In [11]:
from datetime import datetime

In [12]:
datetime.now()

datetime.datetime(2018, 1, 25, 9, 52, 41, 736784)

## 인코딩

In [13]:
unicode_string = '가'

In [14]:
unicode_string.encode('utf8')

b'\xea\xb0\x80'

In [15]:
unicode_string.encode('cp949')

b'\xb0\xa1'

In [16]:
unicode_string.encode('utf16')

b'\xff\xfe\x00\xac'

In [17]:
unicode_string.encode('utf32')

b'\xff\xfe\x00\x00\x00\xac\x00\x00'

In [18]:
utf8_string = unicode_string.encode('utf8')
utf8_string

b'\xea\xb0\x80'

In [19]:
utf8_string.decode('utf8')

'가'

In [20]:
utf8_string.decode('cp949')

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 2: incomplete multibyte sequence

In [21]:
'가나다라마바사아자차카타파하'[1:-1]

'나다라마바사아자차카타파'

In [24]:
'가나다라마바사아자차카타파하'.encode('utf8')[1:-1].decode('utf8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

In [25]:
s = '가나다라마바사아자차카타파하'         # str타입 (유니코드)
utf8_string = s.encode('utf8')

f = open('utf8_string.txt', 'wb')  # write + binary
f.write(utf8_string)
f.close()

In [28]:
f = open('utf8_string.txt', 'rb')  # read + binary
utf8_string = f.read()
f.close()

utf8_string.decode('utf8')  # utf8 -> unicode

'가나다라마바사아자차카타파하'

## open

In [32]:
s = '가나다라마바사아자차카타파하'         # str타입 (유니코드)

# f = open('utf8_string.txt', 'wb')  # write + binary
# utf8_string = s.encode('utf8')
# f.write(utf8_string)
# f.close()

f = open('utf8_string.txt', 'wt', encoding='utf8')  # write + binary
f.write(s)
f.close()

f = open('utf8_string.txt', 'rt', encoding='utf8')
unicode_string = f.read()
print(unicode_string)   # str타입 (유니코드)
f.close()

가나다라마바사아자차카타파하

In [33]:
import requests

In [37]:
image_url = 'http://cfile7.uf.tistory.com/image/26117F3E581EA5550BDC79'

image_data = requests.get(image_url).content

# f = open('twice.jpg', 'wb')
# f.write(image_data)
# f.close()

# open('twice.jpg', 'wb').write(image_data)

In [38]:
import locale
locale.getpreferredencoding(False)

'UTF-8'

In [54]:
# FileNotFoundError -> IOError 계열

# try:
#     f = open('utf8_string.txt', 'rt', encoding='utf8')
#     print(f.read())
#     1/0
# except IOError:
#     print('파일을 찾을 수 없습니다.')
# finally:
#     print('close 합니다.')
#     f.close()

try:
    with open('utf8_string.txt', 'rt', encoding='utf8') as f:
        print(f.read())
        1/0
except IOError:
    print('파일을 찾을 수 없습니다.')

가나다라마바사아자차카타파하

ZeroDivisionError: division by zero

In [50]:
import os
from datetime import datetime

filepath = datetime.now().strftime('logs/%Y/%m/%d') + '/' + 'hello.txt'
# filepath = 'dir1/dir2/dir3/hello.txt'

dirpath = os.path.dirname(filepath)  # 'dir1/dir2/dir3'
if not os.path.exists(dirpath):
    os.makedirs(dirpath)

f = open(filepath, 'wt', encoding='utf8')
f.write('가나다')
f.close()

## 인코딩 탐지하기

In [29]:
import chardet

chardet.detect(utf8_string)

{'confidence': 0.99, 'encoding': 'utf-8', 'language': ''}

In [30]:
cp949_string = s.encode('cp949')
chardet.detect(cp949_string)

{'confidence': 0.99, 'encoding': 'EUC-KR', 'language': 'Korean'}

In [ ]:
# 메모장을 여시고, 메모장에서 "가나다라마바사아자차카타파하" 를 입력하고,
# c:\dev 디렉토리에 저장

f = open('메모장.txt', 'rb')
data = f.read()
f.close()

data.decode('???')  # utf8, cp949

## 순회가능한 객체

In [55]:
가사 = '''내 몸이 확
머리가 휙
돌아가 어때
지금 기분이
우리는 마치
자석 같아
서로를 안고
또 밀쳐내니까
너는 날 미치게 하고
정신 못 차리게 해
그래 알겠지 넌 참
날 기가 막히게 해
너는 날 춤추게 하고
술 없이 취하게 해
그래 알겠지 넌 참
착한 날 독하게 해
우리 둘만의
이 영화에
진짜 주인공은 너였어 baby
그래 넌 오늘도 너답게
화려한 주인공처럼
그저 하던 대로 해
그게 악역이라도
나를 슬프게 해도
넌 너여야만 해
내가 아플지라도
슬픈 엔딩이라도
the show must go on
the show must go on
너는 늘 끝장을 보고
모든 걸 덮으려 해
왜 날개를 달아주고
추락하자 해
너는 늘 착하지 라며
날 눈물 삼키게 하잖아
그래 알겠지 알겠지
넌 날 혹하게 해
우리 둘만의
이 드라마에
진짜 주인공은 너였어 baby
그래 넌 오늘도 너답게
화려한 주인공처럼
그저 하던 대로 해
그게 악역이라도
나를 슬프게 해도
넌 너여야만 해
내가 아플지라도
슬픈 엔딩이라도
the show must go on
the show must go on
그저 하던 대로 해
그게 악역이라도
나를 슬프게 해도
넌 너여야만 해
내가 아플지라도
슬픈 엔딩이라도
the show must go on
the show must go on
you must go on'''

In [56]:
with open('가사.txt', 'wt', encoding='utf8') as f:
    f.write(가사)

In [62]:
with open('가사.txt', 'rt', encoding='utf8') as f:
    # print(f.read())  # 파일 전체 내용 읽기
#     for line in f.read().splitlines():
#         print(line)
    
    for line in f:
        print('#' + line.strip())  # 좌/우 화이트스페이스 제거

#내 몸이 확
#머리가 휙
#돌아가 어때
#지금 기분이
#우리는 마치
#자석 같아
#서로를 안고
#또 밀쳐내니까
#너는 날 미치게 하고
#정신 못 차리게 해
#그래 알겠지 넌 참
#날 기가 막히게 해
#너는 날 춤추게 하고
#술 없이 취하게 해
#그래 알겠지 넌 참
#착한 날 독하게 해
#우리 둘만의
#이 영화에
#진짜 주인공은 너였어 baby
#그래 넌 오늘도 너답게
#화려한 주인공처럼
#그저 하던 대로 해
#그게 악역이라도
#나를 슬프게 해도
#넌 너여야만 해
#내가 아플지라도
#슬픈 엔딩이라도
#the show must go on
#the show must go on
#너는 늘 끝장을 보고
#모든 걸 덮으려 해
#왜 날개를 달아주고
#추락하자 해
#너는 늘 착하지 라며
#날 눈물 삼키게 하잖아
#그래 알겠지 알겠지
#넌 날 혹하게 해
#우리 둘만의
#이 드라마에
#진짜 주인공은 너였어 baby
#그래 넌 오늘도 너답게
#화려한 주인공처럼
#그저 하던 대로 해
#그게 악역이라도
#나를 슬프게 해도
#넌 너여야만 해
#내가 아플지라도
#슬픈 엔딩이라도
#the show must go on
#the show must go on
#그저 하던 대로 해
#그게 악역이라도
#나를 슬프게 해도
#넌 너여야만 해
#내가 아플지라도
#슬픈 엔딩이라도
#the show must go on
#the show must go on
#you must go on

## 재미로 해보는 크롤링 (네이버 웹툰 이미지 다운로드)

아래 코드를 실행 전에 다음 2개 라이브러리가 필요합니다.

```
pip install requests beautifulsoup4
```

In [ ]:
import os
import requests
from bs4 import BeautifulSoup

# 이미지를 가져오고 싶은, 웹툰의 특정 에피소드 주소를 지정해주세요.
ep_url = 'http://comic.naver.com/webtoon/detail.nhn?titleId=662774&no=118&weekday=wed'

res = requests.get(ep_url)
html = res.text

soup = BeautifulSoup(html, 'html.parser')

for tag in soup.select('.view_area img'):
    img_url = tag.get('src')  # ''
    if img_url:
        headers = {'Referer': ep_url}
        res = requests.get(img_url, headers=headers)
        img_data = res.content
        img_name = os.path.basename(img_url)  # url로부터 끝의 파일명을 뽑아냅니다.

        print('다운받는 중 ... ', img_name)

        img_path = '고수/' + img_name
        img_dirpath = os.path.dirname(img_path)
        if not os.path.exists(img_dirpath):
            os.makedirs(img_dirpath)

        with open(img_path, 'wb') as f:
            f.write(img_data)

In [69]:
평점 = {}

In [70]:
평점['고수'] = 9.5

In [71]:
평점

{'고수': 9.5}

In [72]:
'신과함께' in 평점

False

In [73]:
평점['신과함께']

KeyError: '신과함께'

In [74]:
평점['고수']

9.5

In [75]:
평점.get('고수')

9.5

In [77]:
print(평점.get('신과함께'))

None

## 직렬화

In [78]:
obj = {'name': 'AskDjango', 'since': 2015}

In [80]:
import json

json_string = json.dumps(obj)  # str을 반환 (유니코드)

with open("obj.json", "wt", encoding="utf8") as f:
    f.write(json_string)

In [88]:
with open("obj.json", "rt", encoding="utf8") as f:
    json_string = f.read()
    obj = json.loads(json_string)  # obj
    print(obj.keys())
    print(obj['name'], obj['since'])

dict_keys(['name', 'since'])
AskDjango 2015

In [89]:
movies = [
    ["원더", 9.41],
    ["위대한 쇼맨", 9.39],
    ["아이 캔 스피크", 9.34],
    ["1987", 9.28],
    ["러빙 빈센트", 9.19],
    ["뽀로로 극장판 공룡섬 대모험", 9.17],
    ["내 사랑", 9.17],
    ["코코", 9.16],
    ["히트", 9.11],
    ["이터널 선샤인", 9.10],
]
movies

[['원더', 9.41],
 ['위대한 쇼맨', 9.39],
 ['아이 캔 스피크', 9.34],
 ['1987', 9.28],
 ['러빙 빈센트', 9.19],
 ['뽀로로 극장판 공룡섬 대모험', 9.17],
 ['내 사랑', 9.17],
 ['코코', 9.16],
 ['히트', 9.11],
 ['이터널 선샤인', 9.1]]

In [99]:
import csv

with open("영화평점.csv", "wt", encoding="cp949", newline='\n') as f:
    writer = csv.writer(f)

#     for i in range(10):
#         writer.writerow(['원더', 9.41])
#         writer.writerow(['위대한 쇼맨', 9.39])

#     for movie in movies:
#         writer.writerow(movie)

    writer.writerows(movies)

## Pandas

In [121]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [122]:
obj = Series([4, 7, 5, -1])
obj

0    4
1    7
2    5
3   -1
dtype: int64

In [123]:
obj[0]

4

In [124]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [126]:
fruits = Series({'apple': 1000, 'orange': 500, 'banana': 700})
fruits

apple     1000
banana     700
orange     500
dtype: int64

In [128]:
fruits['apple']

1000

In [129]:
fruits.apple

1000

In [130]:
fruits.index

Index(['apple', 'banana', 'orange'], dtype='object')

In [133]:
d1 = Series(['r1', 'r2', 'r3', 'r4', 'r5'])
d1

0    r1
1    r2
2    r3
3    r4
4    r5
dtype: object

In [134]:
d1[1:3]

1    r2
2    r3
dtype: object

In [136]:
d2 = Series(
    data=['r1', 'r2', 'r3', 'r4', 'r5'],
    index=['i1', 'i2', 'i3', 'i4', 'i5'])
d2

i1    r1
i2    r2
i3    r3
i4    r4
i5    r5
dtype: object

In [138]:
d2['i2':'i4']

i2    r2
i3    r3
i4    r4
dtype: object

In [140]:
d3_4x4 = np.arange(16).reshape(4, 4)
d3_4x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
>>> d4 = DataFrame(
        data=d3_4x4,
        index=['Ohio', 'Colorado', 'Utah', 'New York'],
        columns=['one', 'two', 'three', 'four'])
d4

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
d4.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [144]:
d4.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [145]:
d4['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [148]:
column_names = ['four', 'two']
d4[column_names]

          four  two
Ohio         3    1
Colorado     7    5
Utah        11    9
New York    15   13

In [152]:
d4.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [151]:
row_names = ['Colorado', 'Utah']
d4.loc[row_names]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [153]:
d4

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [158]:
d4.loc['Colorado', 'two']

5

In [159]:
d4.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [160]:
d4.loc[['Colorado', 'Utah'], ['two', 'three']]

          two  three
Colorado    5      6
Utah        9     10

In [163]:
d4.loc['Colorado':'New York', ['two', 'three']]

          two  three
Colorado    5      6
Utah        9     10
New York   13     14